version: "3"
services:
  fipe:
    image: fipe-image:latest
    expose:
      - 3000
    restart: always
    container_name: fipe
    environment:
      PORT: 3000
      HTTP_PORT: 3000
      VIRTUAL_HOST: testing.newsun.energy
      LETSENCRYPT_HOST: testing.newsun.energy
      LETSENCRYPT_EMAIL: paulo@newsun.energy
    networks:
      service_network:

networks:
  service_network:
    external: 
      name: nginx-letsencrypt_service_network

